spring:
  config:
    activate:
      on-profile:

  # 데이터 소스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/MAIN?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 42gg
    password: pingPongpower42#

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false

  security:
    oauth2.client:
      registration:
        42:
          client-id: "1eded582676170d1dab786f3586c6a5b73555bad3c94adef564d79c256a08d71"
          client-secret: "bb710418a5a9b8aaa9d969c3e824a29e5b7cd75a9065c53a373aa463a99fb65c"

  # Redis 설정
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379


logging:
  level:
    org.hibernate.SQL: debug

# cors 설정
cors:
  allowed-origins: 'https://42gg.kr,http://42gg.kr,https://api-42gg.shop,http://api-42gg.shop'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: '*'
  allowed-credentials: false
  max-age: 3600

info:
  web:
    frontUrl: 'https://42gg.kr'